.PHONY: help generate generate-rfc test lint package deploy clean

CHROME := google-chrome-stable
TMP_DIR := .tmp
DIST_DIR := dist
RFC_SRC := gux-rfc.md
RFC_GEN := gux_checker/core/_rfc_data.py

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

generate-rfc: $(RFC_SRC) ## Embed gux-rfc.md as base64 into a generated .py
	@python3 -c "\
	import base64, zlib, pathlib;\
	raw = pathlib.Path('$(RFC_SRC)').read_bytes();\
	compressed = zlib.compress(raw, 9);\
	b64 = base64.b64encode(compressed).decode();\
	out = '# GENERATED by make generate-rfc — do not edit\nimport base64, zlib\n\ndef get_rfc() -> str:\n    return zlib.decompress(base64.b64decode(\"' + b64 + '\")).decode()\n';\
	pathlib.Path('$(RFC_GEN)').write_text(out)"
	@echo "Generated $(RFC_GEN)"

generate: generate-rfc ## Screenshot test HTML with headless Chrome into .tmp/
	@mkdir -p $(TMP_DIR)
	$(CHROME) --headless=new --no-sandbox --disable-gpu --disable-software-rasterizer \
		--window-size=960,900 --screenshot=$(TMP_DIR)/dashboard.png --hide-scrollbars \
		file://$(CURDIR)/tests/html/dashboard.html
	@echo "Screenshot saved to $(TMP_DIR)/dashboard.png"

test: ## Run pytest (unit + integration with Chrome)
	uv run pytest -v

lint: ## Run ruff check + format check + lint-imports
	uv run ruff check .
	uv run ruff format --check .
	uv run lint-imports

package: generate-rfc ## Build pyinstaller binary into ./dist/
	uv run pyinstaller gux_checker/__main__.py \
		-n gux-tool \
		--onefile \
		--distpath $(DIST_DIR) \
		--workpath build \
		--specpath build \
		--clean
	@echo "Binary: $(DIST_DIR)/gux-tool"

deploy: package ## Alias for package

clean: ## Remove .tmp/ dist/ build/ *.egg-info
	rm -rf $(TMP_DIR)/*.png $(TMP_DIR)/*.json $(DIST_DIR) build *.egg-info
	@echo "Cleaned."
